### ISSUE TITLE
怎么用啊

### ISSUE THREAD

**Issue by sprite5** [codytan/filebeat-clickhouse#1]
直接替换官网filebeat目录下的主程序文件么,还是放到module里?

**Comment by sprite5** [comment]
没go编译能力,我直接下载的发行版

**Comment by codytan** [comment]
https://github.com/codytan/filebeat-clickhouse/releases
从releases里面下载对应的编译好的执行文件，然后可执行：

`./filebeat -c default.yml` 运行

**Comment by sprite5** [comment]
tables: #insert data config, specify the table and columns. Need to be exactly the same as the field in log file(JSON row format), for compatibility with data types with SQL, the JSON field must be string type
    - table: "table_name"
      columns: ["EventTime", "Label.Label", "Label.Count"] #suport nested type

这部分逻辑有点复杂,需要对应fields里的table,然后还要对fields里的列,我研究了半天也没对上去

**Comment by sprite5** [comment]
最终我用了 http方案,基本和kafka思路一致不需要怎么改动
https://github.com/fufuok/beats-http-output
output.http:
  hosts: ["http://ck:8123?&query=INSERT%20INTO%20default.log%20FORMAT%20JSONEachRow"]
  batch_publish: true
  batch_size: 4096
  format: json_lines

**Comment by codytan** [comment]
> tables: #insert data config, specify the table and columns. Need to be exactly the same as the field in log file(JSON row format), for compatibility with data types with SQL, the JSON field must be string type - table: "table_name" columns: ["EventTime", "Label.Label", "Label.Count"] #suport nested type
> 
> 这部分逻辑有点复杂,需要对应fields里的table,然后还要对fields里的列,我研究了半天也没对上去

对应JSON中的字段到field就好，最终是生成了SQL中的字段，从日志中可以打印看出解析JSON后生成的SQL。Label.Label这个只是嵌套的JSON结构（JSON PAHT)，如果涉及简单的直接对应JSON字段就好。

**Comment by codytan** [comment]
> 最终我用了 http方案,基本和kafka思路一致不需要怎么改动 https://github.com/fufuok/beats-http-output output.http: hosts: ["http://ck:8123?&query=INSERT%20INTO%20default.log%20FORMAT%20JSONEachRow"] batch_publish: true batch_size: 4096 format: json_lines

可以的，HTTP协议相对效率低一些，数量不大可用就好。
